#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = []
# ///
"""PreToolUse guard: block Claude from destroying SOPS encryption footers.

Fires on: PreToolUse events where tool_name is Edit, Write, or MultiEdit.
Every other tool (Bash, Read, Glob, ...) is passed through untouched.

What it blocks (exit 2, reason written to stderr):
  1. Any path whose basename is one of the bootstrap credential artifacts:
         age.key, github-deploy.key, cloudflare-tunnel.json
     These are generated by `task init` and live at the repo root; they must
     never be hand-edited by the agent. See CLAUDE.md > Secrets Management.
  2. Any path matching `*.sops.*` (`.sops.` appears in any path component —
     file or directory) where the file ALREADY exists on disk AND its
     contents look encrypted. "Looks encrypted" means either a line starting
     with `sops:` (the SOPS YAML footer) or the literal substring
     `ENC[AES256`. These two markers match every file that `.sops.yaml` at
     the repo root governs. Direct Edit/Write would corrupt the footer and
     leak plaintext to git.

What it deliberately ALLOWS (exit 0):
  - Write on a non-existent `*.sops.*` path. This is the intended workflow:
    author plaintext, then run `task configure` (or `sops -e -i`) to
    encrypt in place before committing. Blocking new plaintext here would
    break that flow.
  - Edit on an existing `*.sops.*` file that has no encryption markers
    (edge case — shouldn't normally exist, but we don't guess).
  - MultiEdit follows the same rules as Edit / Write.

Fail-open policy: on malformed stdin JSON, missing fields, non-string
file_path, unreadable files (permission denied, dead symlinks, directories,
binary content that won't decode as UTF-8), the hook returns 0. The goal is
a forward-deployed safety net, not a gate — if the hook itself is broken
we would rather let a tool call through than wedge the whole session.

Override: the hook has no env-var bypass. To legitimately modify an
encrypted file, run `sops <file>` outside of Edit/Write (the Bash tool is
not intercepted), or run `task configure` to re-encrypt after plaintext
changes. To disable the hook entirely, remove its entry from
`.claude/settings.json` under PreToolUse.

References: `.sops.yaml` (creation_rules); `CLAUDE.md` Secrets Management.
"""
import json
import re
import sys
from pathlib import Path

PROTECTED_BASENAMES = frozenset({
    "age.key",
    "github-deploy.key",
    "cloudflare-tunnel.json",
})

SOPS_FOOTER = re.compile(r"^sops:", re.MULTILINE)


def is_sops_path(p: Path) -> bool:
    return any(".sops." in part for part in p.parts)


def content_looks_encrypted(text: str) -> bool:
    return bool(SOPS_FOOTER.search(text)) or "ENC[AES256" in text


def reject(file_path: str, reason: str) -> None:
    print(f"Blocked: {file_path} {reason}", file=sys.stderr)


def main() -> int:
    try:
        data = json.load(sys.stdin)
    except json.JSONDecodeError:
        return 0

    tool = data.get("tool_name", "")
    if tool not in {"Edit", "Write", "MultiEdit", "NotebookEdit"}:
        return 0

    tool_input = data.get("tool_input", {}) or {}
    file_path = tool_input.get("file_path", "")
    if not file_path or not isinstance(file_path, str):
        return 0

    path = Path(file_path)

    if path.name.lower() in PROTECTED_BASENAMES:
        reject(
            file_path,
            "is a bootstrap credential. Rotate via `task init` or the "
            "rotate-credential skill instead of editing directly.",
        )
        return 2

    if not is_sops_path(path):
        return 0

    if path.exists():
        try:
            # errors="replace" keeps us fail-open on binary content:
            # the detection heuristic only needs to find ASCII markers
            # (`sops:` / `ENC[AES256`), so replacement bytes can't hide them.
            existing = path.read_text(errors="replace")
        except OSError:
            return 0
        if content_looks_encrypted(existing):
            reject(
                file_path,
                f"is already SOPS-encrypted. Use `sops {file_path}` to edit "
                "in place, then commit. Direct Edit/Write would destroy the "
                "encryption footer.",
            )
            return 2

    return 0


if __name__ == "__main__":
    sys.exit(main())
