---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrepository.yaml
  - ./helmrelease.yaml
  - ./externalsecret.yaml
  - ./httproute.yaml
  - ./dashboard-cluster-health.yaml
  - ./prometheusrule-cilium-memory.yaml
  - ./prometheusrule-cni-plumbing.yaml
  - ./prometheusrule-k8s-2-rejoin-abort.yaml
