---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bakery-server
spec:
  chartRef:
    kind: OCIRepository
    name: bakery-server
  interval: 1h
  values:
    controllers:
      server:
        replicas: 2
        strategy: RollingUpdate
        pod:
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/controller: server
                  app.kubernetes.io/instance: bakery-server
                  app.kubernetes.io/name: bakery-server
        podDisruptionBudget:
          minAvailable: 1
        containers:
          app:
            image:
              repository: ghcr.io/wcygan/kneadybynaturebakery/server
              tag: main-static-cc273ca
              digest: sha256:c4ddd4c4c302ac75ce037da9b601733883e701fbdcaf16b88cf3311b117c27e7
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - /usr/bin/wget
                      - -q
                      - -T
                      - "1"
                      - -O
                      - /dev/null
                      - http://127.0.0.1:8000/
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  timeoutSeconds: 2
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 25m
                memory: 128Mi
              limits:
                memory: 256Mi
    defaultPodOptions:
      imagePullSecrets:
        - name: ghcr-registry-secret
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
    service:
      app:
        controller: server
        ports:
          http:
            port: 8000
    persistence:
      cache:
        type: emptyDir
        advancedMounts:
          server:
            app:
              - path: /var/cache/nginx
      run:
        type: emptyDir
        advancedMounts:
          server:
            app:
              - path: /var/run
