---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./postgres-cluster.yaml
  - ./dragonfly.yaml
  - ./networkpolicy-dragonfly.yaml
  - ./externalsecret-admin.yaml
  - ./externalsecret-s3.yaml
  - ./ingress-tailscale.yaml
  - ./prometheusrule.yaml
