apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:yRdVnGh699gCeQ==,iv:q8eRaxGR4wCr5laay5W6sPSag92m2BWFcT9chKIbNtE=,tag:Bp2VOR6cveQVJPxnmgbNEg==,type:str]
  SECRET_DOMAIN_TWO: ENC[AES256_GCM,data:XKk/42xxWL0OWo4VCN5DW4a8Tthz1yjS,iv:XmQYwRxj7Y8+/43P5IWFb5Ntcc6LD3VvKmZT8s7nb0I=,tag:+YiAtIR4YwDdA5CuCQxyYA==,type:str]
  SECRET_DOMAIN_THREE: ENC[AES256_GCM,data:RQXzf6Tup53wkMY=,iv:xF5cgu1XfVPMUZ7R6rLtvntRjgMu9Mmbn0VIbsPOrPQ=,tag:UZxxo6tURUSyv773kRAquA==,type:str]
  TAILNET_SUFFIX: ENC[AES256_GCM,data:5O4cRS7L0bEv+YRzaMNVCp1+RsU=,iv:wp0kUgKARwhiC8/KMtCbKe/78MznQYnBjwYYk3zZ9CQ=,tag:H38ISYPhCTmFnrPWfkyJlA==,type:str]
sops:
  age:
    - recipient: age1de4xdcq6h5yk4jjyyqe6qws344xsk055rdzvpr79mehvv7q7rdfqnyetjc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZkdmYjE0VXVWdFhPTjJG
        N0pOUUh6MmdCRGNZL2RZMU5zNmVRSFYvNWt3CnhPN3R1VEZIUmVXSldrZFVCU3Fi
        YmE2WTUyY1gwSXZ1MkJENkVBOVZkb2MKLS0tIFhjQXpNeDhQV29yMEg3Tm1Rc3Vi
        VmhTY3lVK1RzVS9WVlVmcUg2TlVCYzgKwylgNY7OnZbFcy4XePRsYouW4Cec/kud
        OX7hYT/0SEVsSOy2jUJoYpQ/FVuu2bH79Hro/7l1WxwIZsB8ytBkng==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-05T01:49:38Z"
  mac: ENC[AES256_GCM,data:KI1FVQOjMw+QkkTZBYahHYuvgxuLW9oO2pyeQtNvIxaDyD2+xIyN394bsF9fjEBZAOW3HRc4QeSxKrum2ZRXbyc1FnLPHZM7Vb3NkmuNflJ3crPxJ1HduucrsAIkRHOAKj471YKtPVQWPcz/TJ+EzLCohi39unGdc8o1CPLwpf4=,iv:rph921uY7kl/xJiZ7jUglK8M4NM6++wKbqqtB4n8yQg=,tag:Pmko/F8qVehmMWdmQHpI4A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
