---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lakehouse-flight-recorder
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/lakehouse/flight-recorder/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: lakehouse
  dependsOn:
    - name: external-secrets
      namespace: external-secrets
    - name: seaweedfs-config
      namespace: storage
  wait: false
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
