---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flight-recorder-raw-s3
  annotations:
    anton.wcygan.net/secret-refresh-class: development
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: flight-recorder-raw-s3
    creationPolicy: Owner
  data:
    - secretKey: RAW_ACCESS_KEY_ID
      remoteRef:
        key: seaweedfs-iceberg/raw-access-key
    - secretKey: RAW_SECRET_ACCESS_KEY
      remoteRef:
        key: seaweedfs-iceberg/raw-secret-key
