---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: clickstack

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./clickstack-operators/ks.yaml
  - ./clickstack-app/ks.yaml
  - ./hyperdx-tailscale-ingress/ks.yaml
