---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./seaweed.yaml
  - ./iceberg-service.yaml
  - ./externalsecret.yaml
  - ./harbor-bucket-cronjob.yaml
  - ./lakehouse-buckets-cronjob.yaml
  - ./lakehouse-s3-smoke-job.yaml
  - ./httproute.yaml
