---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: seaweedfs-bucket-provisioner
    files:
      - provision-buckets.sh=./provision-buckets.sh
      - prefix-marker=./prefix-marker
    options:
      disableNameSuffixHash: true
resources:
  - ./seaweed.yaml
  - ./iceberg-service.yaml
  - ./externalsecret.yaml
  - ./buckets-cronjob.yaml
  - ./spark-events-bucket.yaml
  - ./lakehouse-s3-smoke-job.yaml
  - ./httproute.yaml
