---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-postgres-bootstrap
  annotations:
    anton.wcygan.net/secret-refresh-class: development
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: airflow-postgres-bootstrap
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        fernet-key: '{{ index . "fernet-key" }}'
        jwt-secret: '{{ index . "jwt-secret" }}'
  dataFrom:
    - extract:
        key: airflow-postgres
