---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-postgres-credentials
  annotations:
    anton.wcygan.net/secret-refresh-class: development
spec:
  refreshPolicy: Periodic
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: airflow-postgres-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        connection: "postgresql+psycopg2://{{ .username }}:{{ .password }}@airflow-postgres-rw.airflow.svc.cluster.local:5432/airflow"
        fernet-key: "{{ .fernetKey }}"
        jwt-secret: "{{ .jwtSecret }}"
  data:
    - secretKey: username
      remoteRef:
        key: airflow-postgres/username
    - secretKey: password
      remoteRef:
        key: airflow-postgres/password
    - secretKey: fernetKey
      remoteRef:
        key: airflow-postgres/fernet-key
    - secretKey: jwtSecret
      remoteRef:
        key: airflow-postgres/jwt-secret
