---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: iceberg-demo

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./spark-fixture/ks.yaml
  - ./trino/ks.yaml
