---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: spark-events-reader
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: spark-events-reader
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: seaweedfs-spark-events/reader-access-key
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: seaweedfs-spark-events/reader-secret-key
