spark.history.fs.logDirectory s3a://spark-events/events/
spark.history.fs.cleaner.enabled false
spark.history.fs.update.interval 10s
spark.history.ui.port 18080
spark.hadoop.fs.s3a.endpoint http://seaweedfs-s3.storage.svc.cluster.local:8333
spark.hadoop.fs.s3a.path.style.access true
spark.hadoop.fs.s3a.connection.ssl.enabled false
spark.hadoop.fs.s3a.aws.credentials.provider software.amazon.awssdk.auth.credentials.EnvironmentVariableCredentialsProvider
