---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-source-s3
  annotations:
    anton.wcygan.net/secret-refresh-class: development
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: loki-source-s3
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .shadowAccessKey }}"
        AWS_SECRET_ACCESS_KEY: "{{ .shadowSecretKey }}"
        core-site.xml: |
          <?xml version="1.0"?>
          <configuration>
            <property>
              <name>fs.s3a.bucket.iceberg-raw.access.key</name>
              <value>{{ .rawAccessKey }}</value>
            </property>
            <property>
              <name>fs.s3a.bucket.iceberg-raw.secret.key</name>
              <value>{{ .rawSecretKey }}</value>
            </property>
            <property>
              <name>fs.s3a.bucket.spark-events.access.key</name>
              <value>{{ .sparkEventsWriterAccessKey }}</value>
            </property>
            <property>
              <name>fs.s3a.bucket.spark-events.secret.key</name>
              <value>{{ .sparkEventsWriterSecretKey }}</value>
            </property>
            <property>
              <name>fs.s3a.aws.credentials.provider</name>
              <value>org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider</value>
            </property>
          </configuration>
  data:
    - secretKey: shadowAccessKey
      remoteRef:
        key: seaweedfs-iceberg-shadow/shadow-access-key
    - secretKey: shadowSecretKey
      remoteRef:
        key: seaweedfs-iceberg-shadow/shadow-secret-key
    - secretKey: rawAccessKey
      remoteRef:
        key: seaweedfs-iceberg/raw-access-key
    - secretKey: rawSecretKey
      remoteRef:
        key: seaweedfs-iceberg/raw-secret-key
    - secretKey: sparkEventsWriterAccessKey
      remoteRef:
        key: seaweedfs-spark-events/writer-access-key
    - secretKey: sparkEventsWriterSecretKey
      remoteRef:
        key: seaweedfs-spark-events/writer-secret-key
