---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: food-site-server
spec:
  endpoints:
    - dnsName: food.nu-sync.net
      recordType: CNAME
      targets: [external.nu-sync.net]
