---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: food-site-server
spec:
  parentRefs:
    - name: envoy-external
      namespace: network
      sectionName: https
  hostnames:
    - food.nu-sync.net
  rules:
    - backendRefs:
        - name: food-site-server
          port: 8000
