---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: multus-upstream
  namespace: network
spec:
  interval: 24h
  url: https://github.com/k8snetworkplumbingwg/multus-cni
  ref:
    # renovate: datasource=github-releases depName=k8snetworkplumbingwg/multus-cni
    tag: v4.2.4
  ignore: |
    /*
    !/deployments/multus-daemonset-thick.yml
