---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: echo
spec:
  endpoints:
    - dnsName: "echo.${SECRET_DOMAIN_THREE}"
      recordType: CNAME
      targets: ["external.${SECRET_DOMAIN_THREE}"]
