---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: homepage
spec:
  endpoints:
    - dnsName: "${SECRET_DOMAIN_THREE}"
      recordType: CNAME
      targets: ["external.${SECRET_DOMAIN_THREE}"]
    - dnsName: "www.${SECRET_DOMAIN_THREE}"
      recordType: CNAME
      targets: ["external.${SECRET_DOMAIN_THREE}"]
