---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: homepage
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: flux@anton
        name: flux
      messageTemplate: 'chore(homepage): {{range .Changed.Changes}}{{.NewValue}}{{println}}{{end}}'
    push:
      branch: main
  update:
    path: ./kubernetes/apps/default/homepage
    strategy: Setters
