apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./deployment.yaml
  - ./externalsecret.yaml
  - ./service.yaml
  - ./httproute.yaml
  - ./dnsendpoint.yaml
  - ./imagerepository.yaml
  - ./imagepolicy.yaml
  - ./imageupdateautomation.yaml
images:
  - name: ghcr.io/nu-sync/homepage
    newTag: main-00000017-578dda4 # {"$imagepolicy": "default:homepage:tag"}
