apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./deployment.yaml
  - ./service.yaml
  - ./httproute.yaml
  - ./dnsendpoint.yaml
  - ./imagerepository.yaml
  - ./imagepolicy.yaml
  - ./imageupdateautomation.yaml
images:
  - name: ghcr.io/nu-sync/homepage
    newTag: main-00000008-99b4e8a # {"$imagepolicy": "default:homepage:tag"}
