---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lakehouse
resources:
  - ./namespace.yaml
  - ./airflow-spark-rbac.yaml
  - ./spark-history-server/ks.yaml
  - ./shadow-fixture/ks.yaml
  - ./loki-source/ks.yaml
components:
  - ../../components/sops
