---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-backup-credentials
  annotations:
    anton.wcygan.net/secret-refresh-class: stable
spec:
  refreshPolicy: Periodic
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: longhorn-backup-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .accessKey }}"
        AWS_SECRET_ACCESS_KEY: "{{ .secretKey }}"
        AWS_ENDPOINTS: http://seaweedfs-s3.storage.svc.cluster.local:8333
  data:
    - secretKey: accessKey
      remoteRef:
        key: seaweedfs-longhorn-backup/access-key
    - secretKey: secretKey
      remoteRef:
        key: seaweedfs-longhorn-backup/secret-key
