---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./longhorn-config/ks.yaml
  - ./longhorn-backup-config/ks.yaml
  - ./longhorn/ks.yaml
  - ./seaweedfs/ks.yaml
  - ./seaweedfs-config/ks.yaml
